<? $home = $pages->get('/');?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title><?php echo $page->title ;?></title>

    <!-- CSS -->
    <link href="<?php echo $config->urls->templates; ?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $config->urls->templates; ?>css/style.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body id="<?php echo $page->template ;?>">